from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

from .views import (
    download_cash_memo, salesman_list, delete_salesman, customer_list, delete_customer, product_list, delete_product,
    pos_dashboard, save_sale, all_sales, delete_sale, stockaddjust, update_stock, salesaddjust, update_sales,
    transaction_list, delete_transaction, dashboard, salespayjust, salesman_pay, expence_list, delete_expence,
    filter_sales, delete_adai, update_adai, filter_adai, filter_customer_sales, login_view, logout_view, customer_ledger,
    add_expence, update_expence, supplier_ledger, download_salesman_report, export_salesman_report_excel, export_salesman_payment_excel, salesman_login, salesman_logout,
    salesman_pos, save_pending_sale, pending_sales, approve_sale, reject_sale, upload_products, product_report,
    marketing_cost, marketing_cost_list, delete_marketing_cost, profit_report, update_customer, update_salesman,update_product,update_transaction,
    homepage, product_detail, cart, checkout, place_order, api_products, api_product_detail, all_orders,
    upload_customers, export_customers_excel, export_all_sales_excel, export_adai_excel,delete_supplier, update_supplier,
    request_password_reset_code, reset_admin_credentials,
)

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('', login_view, name='login'),
    path('auth/request-reset-code/', request_password_reset_code, name='request_password_reset_code'),
    path('auth/reset-credentials/', reset_admin_credentials, name='reset_admin_credentials'),
    path('homepage', homepage, name='homepage'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('salesmen/', salesman_list, name='salesman_list'),
    path('salesmen/delete/<str:salesman_id>/', delete_salesman, name='delete_salesman'),
    path('customer/', customer_list, name='customer_list'),
    path('customer/delete/<str:customer_id>/', delete_customer, name='delete_customer'),
    path('customer/upload-excel/', upload_customers, name='upload_customers'),
    path('customer/export-excel/', export_customers_excel, name='export_customers_excel'),
    path('products/', product_list, name='product_list'),
    path('products/delete/<str:product_id>/', delete_product, name='delete_product'),
    path('sales/', pos_dashboard, name='pos_dashboard'),
    path('save-sale/', save_sale, name='save_sale'),
    path('all-sales/', all_sales, name='all_sales'),
    path('all-sales/export-excel/', export_all_sales_excel, name='export_all_sales_excel'),
    path('orders/', all_orders, name='all_orders'),
    path('stockaddjust/', stockaddjust, name='stockaddjust'),
    path('update-stock/', update_stock, name='update_stock'),
    path('salesaddjust/', salesaddjust, name='salesaddjust'),
    path('delete_adai/<str:adai_id>/', delete_adai, name='delete_adai'),
    path('update_adai/<str:adai_id>/', update_adai, name='update_adai'),
    path('update-sales/', update_sales, name='update_sales'),
    path('all-sales/delete/<str:sale_id>/', delete_sale, name='delete_sale'),
    path('download-cash-memo/<str:sale_id>/', download_cash_memo, name='download_cash_memo'),
    path('transactions/', transaction_list, name='transaction_list'),
    path('transactions/delete/<str:transaction_id>/', delete_transaction, name='delete_transaction'),
    path('salesmanpaydata/', salespayjust, name='salespayjust'),
    path('updatesalespay/', salesman_pay, name='salesman_pay'),
    path('expence_list/', expence_list, name='expence_list'),
    path('delete_expence/delete/<str:transaction_id>/', delete_expence, name='delete_expence'),
    path('delete_supplier/', delete_supplier, name='delete_supplier'),
    path('update_supplier/', update_supplier, name='update_supplier'),
    path('filter_sales/', filter_sales, name='filter_sales'),
    path('filter_adai/', filter_adai, name='filter_adai'),
    path('filter_adai/export-excel/', export_adai_excel, name='export_adai_excel'),
    path('filter_customer_sales/', filter_customer_sales, name='filter_customer_sales'),
    path('customer_ledger/', customer_ledger, name='customer_ledger'),
    path('add_expence/', add_expence, name='add_expence'),
    path('update_expence/<int:expence_id>/', update_expence, name='update_expence'),
    path('supplier_ledger/', supplier_ledger, name='supplier_ledger'),
    path('download_salesman_report/', download_salesman_report, name='download_salesman_report'),
    path('filter_sales/export-excel/', export_salesman_report_excel, name='export_salesman_report_excel'),
    path('salesmanpaydata/export-excel/', export_salesman_payment_excel, name='export_salesman_payment_excel'),
    path('salesman/login/', salesman_login, name='salesman_login'),
    path('salesman/logout/', salesman_logout, name='salesman_logout'),
    path('salesman/pos/', salesman_pos, name='salesman_pos'),
    path('save_pending_sale/', save_pending_sale, name='save_pending_sale'),
    path('pending_sales/', pending_sales, name='pending_sales'),
    path('approve_sale/<int:sale_id>/', approve_sale, name='approve_sale'),
    path('reject_sale/<int:sale_id>/', reject_sale, name='reject_sale'),
    path('upload-products/', upload_products, name='upload_products'),
    path('product-report/', product_report, name='product_report'),
    path('marketing_cost/', marketing_cost, name='marketing_cost'),
    path('marketing_cost_list/', marketing_cost_list, name='marketing_cost_list'),
    path('delete_marketing_cost/<int:cost_id>/', delete_marketing_cost, name='delete_marketing_cost'),
    path('profit_report/', profit_report, name='profit_report'),
    path('update_customer/<int:customer_id>/', update_customer, name='update_customer'),
    path('update_salesman/<int:salesman_id>/', update_salesman, name='update_salesman'),
    path('update_product/<int:product_id>/', update_product, name='update_product'),
    path('update_transaction/<int:transaction_id>/', update_transaction, name='update_transaction'),
    # Ecommerce routes
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('place-order/', place_order, name='place_order'),
    path('api/products/', api_products, name='api_products'),
    path('api/product/<int:product_id>/', api_product_detail, name='api_product_detail'),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

