# Generated by Django 4.1.5 on 2025-05-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('nid', models.CharField(max_length=50)),
                ('due', models.FloatField(default=0)),
                ('Advance', models.FloatField(default=0)),
                ('Paid', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.CharField(max_length=255)),
                ('suplier', models.CharField(max_length=100)),
                ('due', models.FloatField(default=0)),
                ('advance', models.FloatField(default=0)),
                ('total_pay', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0)),
                ('add_stock', models.FloatField(default=0)),
                ('production_cost', models.FloatField(default=0)),
                ('total_sales', models.FloatField(default=0)),
                ('total_stock', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('nid', models.CharField(max_length=50)),
                ('comission', models.FloatField(default=0)),
                ('salescomission', models.FloatField(default=0)),
                ('Due', models.FloatField(default=0)),
                ('Paid', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.CharField(max_length=255)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(default=list)),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('less', models.FloatField(default=0)),
                ('payment_received', models.FloatField(default=0)),
                ('due', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comission', models.FloatField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='Adai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.FloatField(default=0)),
                ('advance', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('sales_comission', models.FloatField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.salesman')),
            ],
        ),
    ]
