# Generated by Django 4.1.5 on 2025-06-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('Transportation', 'Transportation'), ('Hotel', 'Hotel'), ('Food', 'Food'), ('Mobile', 'Mobile')], max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salesman')),
            ],
        ),
    ]
