# Generated by Django 4.1.5 on 2025-06-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_marketingcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesman',
            old_name='salescomission',
            new_name='basic_salary',
        ),
    ]
