# Generated by Django 4.1.5 on 2025-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_salescomission_salesman_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='salescomission',
            field=models.FloatField(default=0),
        ),
    ]
