# Generated by Django 4.1.5 on 2025-06-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_salesman_salescomission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salesman')),
            ],
        ),
    ]
