# Generated by Django 4.1.5 on 2025-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_salesmansalarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcost',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
