# Generated by Django 4.1.5 on 2025-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_marketingcost_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adai',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
