# Generated by Django 4.1.5 on 2025-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_adai_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_incash',
            field=models.FloatField(default=0),
        ),
    ]
