# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_less_products',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='less_input',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsale',
            name='total_less_products',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsale',
            name='less_input',
            field=models.FloatField(default=0),
        ),
    ]
