# Generated by Django 5.2.10 on 2026-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0011_sale_total_less_products_less_input_pendingsale_total_less_products_less_input",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="advance_used",
            field=models.FloatField(default=0),
        ),
    ]
